### ISSUE TITLE
le-utils 0.0.11 broken on python 2

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/le-utils#27]
After upgrading to the latest Kolibri develop branch (which uses le-utils 0.0.11) can no longer run on python 2. Running on python 3 works fine.

```
(le)~/P/l/r/kolibri (develop) $ yarn
yarn install v0.19.1
$ node ./frontend_build/src/npm_deprecation_warning.js
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ node ./frontend_build/src/install_dependencies.js
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "kolibri/utils/cli.py", line 540, in main
    initialize(debug=debug)
  File "kolibri/utils/cli.py", line 141, in initialize
    django.setup()
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "kolibri/content/models.py", line 19, in <module>
    from le_utils.constants.languages import LANGUAGE_DIRECTIONS
ImportError: No module named languages
child_process.js:533
    throw err;
    ^

Error: Command failed: python -m kolibri manage webpack_json -- --outputfile /var/folders/n9/k997qvqs3f7_m_310crwsxyc0000gp/T/11773-1471-1572598.wft27ta9k9.json
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "kolibri/utils/cli.py", line 540, in main
    initialize(debug=debug)
  File "kolibri/utils/cli.py", line 141, in initialize
    django.setup()
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "kolibri/content/models.py", line 19, in <module>
    from le_utils.constants.languages import LANGUAGE_DIRECTIONS
ImportError: No module named languages

    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at module.exports (/Users/d/Projects/learning_equality/repos/kolibri/frontend_build/src/read_webpack_json.js:10:3)
    at Object.<anonymous> (/Users/d/Projects/learning_equality/repos/kolibri/frontend_build/src/install_dependencies.js:6:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by indirectlylit** [comment]
invalid - I had previously installed `le-utils` for local dev and this required manual modification of my virtual environment's site packages to remove: https://stackoverflow.com/a/18818891
